# Generated by Django 4.2.1 on 2023-05-26 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100)),
                ('project_client_name', models.CharField(max_length=100)),
                ('project_client_number', models.CharField(max_length=20)),
                ('project_client_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(choices=[('Office', 'Office'), ('Work From Home', 'Work From Home')], max_length=100)),
                ('type', models.CharField(choices=[('New', 'New'), ('Rework', 'Rework'), ('Edit', 'Edit')], max_length=100)),
                ('type2', models.CharField(choices=[('Other', 'Other'), ('Poster', 'Poster'), ('Video', 'Video'), ('Branding', 'Branding'), ('Brochure', 'Brochure'), ('Packaging', 'Packaging'), ('Developing', 'Developing')], max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Approved', 'Aprooved')], default='Pending', max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_photo', models.ImageField(upload_to='employees_photo')),
                ('employees_number', models.CharField(max_length=20)),
                ('employees_job', models.CharField(max_length=100)),
                ('employees_address', models.CharField(max_length=20)),
                ('employee_email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
