# Generated by Django 4.2.1 on 2023-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='employees_job',
            field=models.CharField(choices=[('Graphic Designer', 'Graphic Designer'), ('Content Writer', 'Content Writer'), ('Digital Marketing', 'Digital Marketing'), ('Coordinator', 'Coordinator'), ('Intern', 'Intern')], max_length=100),
        ),
    ]
